version: '3'
services: 
 fruit: 
  image: linuxacademycontent/fruit-service:1.0.1
  ports:
   - 8081:80
  environment:
   - FRUIT_HOST=172.31.29.245
   - FRUIT_PORT=8081
    
 vegetable:
  image: linuxacademycontent/vegetable-service:1.0.0
  ports:
   - 8082:80
  environment:
   - VEGETABLE_HOST=172.31.29.245
   - VEGETABLE_PORT=8082
 
 allproduct:
  image: linuxacademycontent/all-products:1.0.0
  ports:
   - 8080:80
  depend_on:
   - fruit
   - vegetable
  environment:
   - FRUIT_HOST=172.31.29.245
   - FRUIT_PORT=8081
   - VEGETABLE_HOST=172.31.29.245
   - VEGETABLE_PORT=8082
